// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://muxbpyppvqnqfklcmqdb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im11eGJweXBwdnFucWZrbGNtcWRiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2NzYzOTIsImV4cCI6MjA3MDI1MjM5Mn0.xkrnLDzMTff6mXz7dd4GAqjSZ8_eaKjWSs4AJMZPH_4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});